### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [dracula/konsole#1]
Hello @rishabhsrao!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by rishabh-ink** [comment]
Hi @zenorocha Sorry about the delayed reply; I missed the notification. Sure, that's great! I'll transfer the repo to the Dracula org.

**Comment by zenorocha** [comment]
That's great! I just sent you an invitation to join the Dracula organization. Once you accept it, you can move the repository and rename it to `konsole`.

After that, we'll need to add a new page on draculatheme.com. Can you send a pull request on https://github.com/dracula/dracula.github.io if you all the instructions people need to install this theme?

Thanks!

**Comment by rishabh-ink** [comment]
Sure, I've requested the transfer to the Dracula organization. I'll send the pull request on [dracula/dracula.github.io](https://github.com/dracula/dracula.github.io) shortly. Thank you!

**Comment by zenorocha** [comment]
You don't need to request transfer, I added all the permissions for you to transfer directly, you can just go to https://github.com/rishabhsrao/konsole/settings and click transfer.

**Comment by rishabh-ink** [comment]
@zenorocha Great, I've transferred the repo to [dracula/konsole](https://github.com/dracula/konsole) and added the instructions in [pull request #35](https://github.com/dracula/dracula.github.io/pull/35). Please merge it in if everything's okay. Thank you!

**Comment by zenorocha** [comment]
Awesome! We have everything in place now ;)
