### ISSUE TITLE
Npm install output legibility is compromised

### ISSUE THREAD

**Issue by eronh** [dracula/konsole#2]
![image](https://user-images.githubusercontent.com/9641348/29391330-f9e5cebe-82cc-11e7-8224-148f79c33d47.png)

**Comment by ekaitz-zarraga** [comment]
This issue happens because the order of the colors doesn't fit the standard terminal ones.
See PR #4  please and see if it solves your issue.

**Comment by ekaitz-zarraga** [comment]
npm list looks fine with the #4 patch.
![image](https://user-images.githubusercontent.com/10085143/62428052-fa5e2b00-b6fc-11e9-89ae-7d33fe0e2a56.png)

**Comment by eronh** [comment]
Hey @ekaitz-zarraga :wave: 

It looks fine now, great work!

Thx!

**Comment by ekaitz-zarraga** [comment]
No problem.
It's still not merged in master, we may need to keep this issue open.

**Comment by rishabh-ink** [comment]
Thanks for submitting a fix and verifying the changes. I've merged PR #4 into `master`.
