### ISSUE TITLE
Bad colors in the text editor Midnight Commander (mcedit) and Midnight Commander(mc)

### ISSUE THREAD

**Issue by timurchak** [dracula/konsole#3]
See screenshot
![mc_colors](https://user-images.githubusercontent.com/40434855/58625244-b9036680-82da-11e9-8ef5-dcae7de413a1.png)
![mcedit_colors](https://user-images.githubusercontent.com/40434855/58625245-b99bfd00-82da-11e9-8cd3-ae50f90e9851.png)

**Comment by ekaitz-zarraga** [comment]
This issue happens because the order of the colors doesn't fit the standard terminal ones.
See PR #4 4 please and see if it solves your issue.

**Comment by ekaitz-zarraga** [comment]
Looks it works fine with #4 
![image](https://user-images.githubusercontent.com/10085143/62428071-8b350680-b6fd-11e9-832b-c21602ffa032.png)

**Comment by rishabh-ink** [comment]
Thanks for submitting a fix and verifying the changes. I've merged PR #4 into `master`.
