### ISSUE TITLE
Yellow ANSI color on Konsole

### ISSUE THREAD

**Issue by jaeseok-park** [dracula/konsole#5]
I'm using Konsole on CentOS 7 KDE.
I applied Dracula theme for Konsole as the instruction https://draculatheme.com/konsole/.
But, yellow color and magenta seem to be wrong.

![ansi](https://user-images.githubusercontent.com/8565274/70438478-4701aa80-1ad1-11ea-91bf-a035b7b6d722.png)

The above screenshot is the result of `cat AnsiEsc.txt` from https://raw.githubusercontent.com/vim-scripts/Improved-AnsiEsc/master/doc/AnsiEsc.txt.

I guess yellow and magenta are switched.
Could you fix this or help me solve this issue, please?

@rishabhsrao

**Comment by rishabh-ink** [comment]
Hi! My apologies for the late reply. I just tried this with Kubuntu 20.04 with Konsole 19.12.3. The colors seem fine to me. Here's a screenshot.

![Screenshot_20200524_081724](https://user-images.githubusercontent.com/342789/82749239-40bd6d00-9d97-11ea-8aad-343cd10d9a0c.png)

Please check your profile settings in Konsole or try reinstalling the color scheme.

I'll close this issue for now. Feel free to reopen if you'd like to discuss further. Thanks!
